language: c

sudo: false

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    - RACKET_VERSION: HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install -in threading --auto --link $TRAVIS_BUILD_DIR

script:
  - raco test -p threading
  - raco cover -bf coveralls -d $TRAVIS_BUILD_DIR/coverage -p threading
